### ISSUE TITLE
About TotalLoss in model.RankingLoss

### ISSUE THREAD

**Issue by karim-moon** [yixinL7/SimCLS#13]
Thank you for the nice research and the paper is pretty readable and very intuitive.

But when I read the code some question came to my mind.

https://github.com/yixinL7/SimCLS/blob/1f08d260dce0668241e9d2fb9eed57cc6b0e60f2/model.py#L7-L10

I think the variable TotalLoss at line number 10 will always be 0.
Ofcourse it would be change from the next line by the candi and summary score.
Is it for just referencing before for loop?

Thanks

**Comment by yixinL7** [comment]
Thank you for your interest in our work!
> Is it for just referencing before for loop?
Yes, it is. Mostly for referencing.

**Comment by karim-moon** [comment]
Thank you for answering
