### ISSUE TITLE
Any try on other generation task ?

### ISSUE THREAD

**Issue by Hannibal046** [yixinL7/SimCLS#14]
Hi, thanks for your great work. I am wondering have you ever tried this general idea to other NLG tasks like dialogue or NMT? Hoping to get some insights from you guys !

**Comment by yixinL7** [comment]
Hi! I have thought about applying this idea to NLG tasks before but I didn't get the chance to try it myself. (It could be interesting :)).  I think the general rule of thumb is to keep in mind the difference among different NLG tasks and to verify if the candidate summaries are diverse enough (both lexically and semantically).

**Comment by Hannibal046** [comment]
Hi, thanks for reply ! It helps me a lot. And I have another question about reranking part. Did you conduct some preliminary experiments on other reranking module ? Like casting it into a regression problem by `(article,candidate) --> rouge` or something like this ?

**Comment by yixinL7** [comment]
We did try the regression approach in our preliminary experiments and found that the re-ranking loss worked better. 
There is an ACL2022 paper "[SummaReranker: A Multi-Task Mixture-of-Experts Re-ranking Framework for Abstractive Summarization](https://arxiv.org/pdf/2203.06569.pdf)" which formulates the re-ranking as a binary classification task.

**Comment by Hannibal046** [comment]
OK, I will check this later. Really helps me a lot. Thanks !
