### ISSUE TITLE
On well trained models

### ISSUE THREAD

**Issue by gaozhiguang** [yixinL7/SimCLS#2]
Hi, yixinL7
very nice work. Do you mind sharing your trained model.
I don't have much resources to train by myself.
Thanks.

**Comment by yixinL7** [comment]
Hi, thank you for your interest in our work. We have updated this repo with the trained models.

**Comment by ramgj28** [comment]
Thank you so much for providing the trained models. I am actually an
engineering undergrad who is interested in deep learning. I am intrigued by
your work and am trying to learn from it. Thanking you again for providing
the code along with the paper so students like me can learn better.


Yours sincerely
Ramgopal J

**Comment by ramgj28** [comment]
hey i cant find the trained models, can you mention where it is?

**Comment by yixinL7** [comment]
![image](https://user-images.githubusercontent.com/51046084/122784114-2dbdea80-d280-11eb-9a1c-c41a392571fe.png)
Links are embedded here :)

**Comment by ramgj28** [comment]
oh thank you, my bad ;)
