### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.0.15 (from -r requirements.txt (line 48)) (from versions: 1.3.0) ERROR: No matching distribution found for mkl-fft==1.0.15 (from -r requirements.txt (line 48))

### ISSUE THREAD

**Issue by Ga091an** [yixinL7/SimCLS#7]

**Comment by yixinL7** [comment]
We tried to install the environment from scratch using the provided files, and we didn't encounter this problem.

Could you provide more details about your installation procedure? It would be helpful to find the problem. 

Thank you :)

**Comment by Ga091an** [comment]
> We tried to install the environment from scratch using the provided files, and we didn't encounter this problem.
> 
> Could you provide more details about your installation procedure? It would be helpful to find the problem.
> 
> Thank you :)

I use 
`pip install xxx`
instead of 
`pip3 install xxx`,
then everything goes fine :)
